name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21.1.0'

    - name: Change to Project Directory
      run: cd probloom

    - name: Install Dependencies
      run: npm install
      working-directory: ./probloom

    - name: Run Jest Unit Tests
      run: npm test -- --watchAll=false
      working-directory: ./probloom

    - name: Build
      run: npm run build
      working-directory: ./probloom

    - name: Install Cypress Dependencies
      run: npm install cypress
      working-directory: ./probloom

    - name: Run Cypress Integration Tests
      uses: cypress-io/github-action@v4.1.0
      with:
        start: npm run start # Replace with your custom server start script
        wait-on: 'http://localhost:3000'
        wait-on-timeout: 60
        config-file: cypress.config.ts # Update this line
        working-directory: ./probloom